import bcrypt from 'bcryptjs';


const data = {
  users: [
    {
      name: 'Dami Lola',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      phone: "08078158294",
      isAdmin: true,
    },
    {
      name: 'Ogooluwanick Olu',
      email: 'ogooluwanick@gmail.com',
      password: bcrypt.hashSync('123456'),
      phone: "08072948158",
      isAdmin: false,
      isStaff:true ,
    },
    {
        name: 'Jane',
        email: 'jane@example.com',
        password: bcrypt.hashSync('123456'),
        phone: "08072948158",
        isAdmin: false,
      },
  ],
  banner:[
        {
                image:"../assets/headphones_a_1.webp",
                buttonText: "Shop Now",
                product: "Beats Solo Air",
                slug: "beats-solo-air",
                desc: "Best headphones around.",
                smallText: "Beats Solo Air",
                midText: "SUMMER SALE",
                largeText1: "FINE",
                largeText2: "",
                discount: "",
                saleTime: "",
        },
        {
                image:"../assets/banner-headPhone.webp",
                buttonText: "Shop Now",
                product: "Beats Solo Air",
                slug: "beats-solo-air",
                desc: "Best headphones around.",
                smallText: "Beats Solo Air",
                midText: "SUMMER SALE",
                largeText1: "FINE",
                largeText2: "SMILE",
                discount: "20% OFF",
                saleTime: "10th OCT to 10TH NOV",
        }
  ],
  products: [
    {
      name: 'Earphones max',
      slug: 'earphones-max',
      category: 'Electronics',
      image: ["../assets/" , "../assets/" , "../assets/" , "../assets/"],
      price: 14000,
      brand: 'Max',
      rating: 2,
      numReviews: 2,
      countInStock: 3,
      description: 'Earphones max will forever change the way you use headphones. Whenever you pull your AirPods out of the charging case, they instantly turn on and connect to your iPhone, Apple Watch, iPad, or Mac. 1. Audio automatically plays as soon as you put them in your ears and pauses when you take them out.',
    },
    {
      name: 'Sliver Wolfs Headset',
      slug: 'sliver-wolfs-headset',
      category: 'Electronics',
      image: ["../assets/" , "../assets/" , "../assets/" , "../assets/"],
      price: 15000,
      brand: 'Max',
      rating: 0,
      numReviews: 8,
      countInStock: 20,
      description: 'Headphones are a pair of padded speakers which you wear over your ears in order to listen to a radio or recorded music, or for using a phone without other people hearing it.',
    },
    {
      name: 'Black Fire Headsets',
      slug: 'black-fire-headsets',
      category: 'Electronics',
      image: ["../assets/" , "../assets/" , "../assets/" , "../assets/"],
      price: 30000,
      brand: 'Max',
      rating: 3.5,
      numReviews: 2,
      countInStock: 100,
      description: 'Headphones are a pair of small speakers used for listening to sound from a computer, music player or other such electronic device',
    },
    {
      name: 'Apple Watch Series 5',
      slug: 'apple-watch-series-5',
      category: 'Electronics',
      image: ["../assets/" , "../assets/" , "../assets/" , "../assets/"],
      price: 8000,
      brand: 'Max',
      rating: 5,
      numReviews: 3,
      countInStock: 10,
      description: 'Apple Watch is a wearable smartwatch that allows users to accomplish a variety of tasks, including making phone calls, sending text messages and reading email. Apple released the Apple Watch on April 24, 2015.',
    },
    {
      name: 'Beats HeadPhones',
      slug: 'beats-headphones',
      category: 'Electronics',
      image: ["../assets/" , "../assets/" , "../assets/" , "../assets/"],
      price: 19000,
      brand: 'Max',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'The original under desk headphone mount. Trusted on over 100,000 desks worldwide. Installs in seconds. Holds ultra-strong: New European made 3M adhesive.',
    },
    {
      name: 'BoomTube',
      slug: 'boom-tube',
      category: 'Electronics',
      image: ["../assets/" , "../assets/" , "../assets/" , "../assets/"],
      price: 110000,
      brand: 'Max',
      rating: 4.8,
      numReviews: 47,
      countInStock: 42,
      description: 'BoomTube is designed to go wherever you do and fill the room with a rich clear sound field that has as much power  BoomTube is designed to go wherever you do and fill the room with a rich clear sound field that has as much power as it does definition. With a sleek interface, the BoomTube is intuitive to use and brings people together with engaging features for a unique shared listening experience.',
    },
    {
      name: 'Louis Vuitton Shirt',
      slug: 'louis-vuitton-shirt',
      category: 'Shirts',
      image: ["../assets/" , "../assets/" , "../assets/" , "../assets/"],
      price: 28000,
      brand: 'Louis Vuitton',
      rating: 3.9,
      numReviews: 5,
      countInStock: 12,
      description: 'Smart looking shirt',
    },
    {
      name: 'Red Kap Shirt',
      slug: 'red-kap-shirt',
      category: 'Shirts',
      image: ["../assets/" , "../assets/" , "../assets/" , "../assets/"],
      price: 12000,
      brand: 'Red Kap',
      rating: 2.,
      numReviews: 15,
      countInStock: 100,
      description: 'Smart looking shirt',
    },
    {
      name: 'Russel Shirt',
      slug: 'russel-shirt',
      category: 'Shirts',
      image: ["../assets/" , "../assets/" , "../assets/" , "../assets/"],
      price: 4000,
      brand: 'Russel',
      rating: 4.,
      numReviews: 5,
      countInStock: 10,
      description: 'Smart looking shirt',
    },
    {
      name: 'Double Pants',
      slug: 'Double-pants',
      category: 'Pants',
      image: ["../assets/" , "../assets/" , "../assets/" , "../assets/"],
      price: 9500,
      brand: 'Zara',
      rating: 5,
      numReviews: 7,
      countInStock: 10,
      description: 'Some popular pants',
    },
    {
      name: 'Flare Pants',
      slug: 'Flare-pants',
      category: 'Pants',
      image: ["../assets/" , "../assets/" , "../assets/" , "../assets/"],
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 30,
      description: 'Some popular pants',
    },
  ],
};

export default data;