import bcrypt from 'bcryptjs';


const data = {
  users: [
    {
      name: 'Dami Lola',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      phone: "08078158294",
      isAdmin: true,
    },
    {
      name: 'Ogooluwanick Olu',
      email: 'ogooluwanick@gmail.com',
      password: bcrypt.hashSync('123456'),
      phone: "08072948158",
      isAdmin: false,
      isStaff:true ,
    },
    {
        name: 'Jane',
        email: 'jane@example.com',
        password: bcrypt.hashSync('123456'),
        phone: "08072948158",
        isAdmin: false,
      },
  ],
  banner:[
        {
                image:"../assets/headphones_a_1.webp",
                buttonText: "Shop Now",
                product: "Beats Solo Air",
                slug: "beats-solo-air",
                desc: "Best headphones around.",
                smallText: "Beats Solo Air",
                midText: "SUMMER SALE",
                largeText1: "FINE",
                largeText2: "",
                discount: "",
                saleTime: "",
        },
        {
                image:"../assets/banner-headPhone.webp",
                buttonText: "Shop Now",
                product: "Beats Solo Air",
                slug: "beats-solo-air",
                desc: "Best headphones around.",
                smallText: "Beats Solo Air",
                midText: "SUMMER SALE",
                largeText1: "FINE",
                largeText2: "SMILE",
                discount: "20% OFF",
                saleTime: "10th OCT to 10TH NOV",
        }
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;